# Generated by Django 4.2.6 on 2023-11-15 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('almacenista', 'Almacenista'), ('repartidor', 'Repartidor'), ('administrador', 'Administrador')], default='cliente', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('codigoHex', models.CharField(max_length=7)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en proceso', 'EN PROCESO'), ('entregado', 'ENTREGADO'), ('cancelado', 'CANCELADO'), ('pagado', 'PAGADO')], default='en proceso', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('subtotal', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendiente', 'PENDIENTE'), ('aceptada', 'ACEPTADA'), ('rechazada', 'RECHAZADA'), ('finalizada', 'FINALIZADA')], default='pendiente', max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('precio', models.FloatField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('XL', 'XL'), ('X', 'X'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TallaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadInventario', models.IntegerField(default=0)),
                ('minStock', models.IntegerField()),
                ('maxStock', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.talla')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('procesando', 'PROCESANDO'), ('preparando', 'PREPARANDO'), ('en transito', 'EN TRANSITO'), ('entregado', 'ENTREGADO')], default='procesando', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('subtotal', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_totales', to=settings.AUTH_USER_MODEL)),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.iva')),
                ('repartidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_repartidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.tallaproducto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.venta')),
            ],
        ),
        migrations.CreateModel(
            name='PruebasDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.devolucion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.producto')),
            ],
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='producto')),
                ('active', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='sport4all.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=5)),
                ('calle', models.CharField(max_length=20)),
                ('numeroExterno', models.CharField(max_length=5)),
                ('numeroInterno', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='devolucion',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.ventaproducto'),
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.tallaproducto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.iva'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.provedor'),
        ),
    ]
