# Generated by Django 4.2.6 on 2023-10-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoproducto',
            name='foto',
            field=models.ImageField(upload_to='producto'),
        ),
    ]
