# Generated by Django 4.2.6 on 2023-12-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducto',
            name='precioUnitario',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
