# Generated by Django 4.2.6 on 2023-10-21 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iva',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
