# Generated by Django 4.2.6 on 2023-11-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='sport4all.producto'),
        ),
    ]
