# Generated by Django 4.2.6 on 2023-12-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0002_alter_ventaproducto_preciounitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallaproducto',
            name='talla',
            field=models.CharField(choices=[('XL', 'XL'), ('X', 'X'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], max_length=2),
        ),
    ]
