# Generated by Django 4.2.6 on 2023-11-17 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0003_remove_producto_color_compraproducto_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocarrito',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sport4all.color'),
            preserve_default=False,
        ),
    ]
