# Generated by Django 4.2.6 on 2023-10-21 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0003_alter_compra_fecha_alter_devolucion_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('codigoHex', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='tallaproducto',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sport4all.color'),
            preserve_default=False,
        ),
    ]
