# Generated by Django 4.2.6 on 2023-11-20 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0004_productocarrito_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tallaproducto',
            options={'verbose_name': 'Inventario'},
        ),
        migrations.AlterField(
            model_name='color',
            name='codigoHex',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='subtotal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='talla',
            name='talla',
            field=models.CharField(choices=[('XL', 'XL'), ('X', 'X'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sport4all.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='colorproducto',
            unique_together={('producto', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='compraproducto',
            unique_together={('producto', 'color', 'compra')},
        ),
        migrations.AlterUniqueTogether(
            name='fotoproducto',
            unique_together={('foto', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'marca', 'descripcion', 'precio')},
        ),
        migrations.AlterUniqueTogether(
            name='tallaproducto',
            unique_together={('producto', 'talla')},
        ),
        migrations.AlterUniqueTogether(
            name='ventaproducto',
            unique_together={('producto', 'color', 'venta')},
        ),
    ]
