# Generated by Django 4.2.6 on 2023-10-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0004_color_tallaproducto_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='subtotal',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.preciohistorico'),
        ),
    ]
