# Generated by Django 4.2.6 on 2023-10-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0005_compra_subtotal_compra_total_venta_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraproducto',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.compra'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.ventaproducto'),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.venta'),
        ),
    ]
