# Generated by Django 4.2.6 on 2023-10-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0006_alter_compraproducto_compra_alter_devolucion_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tallaproducto',
            name='cantidadInventario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
    ]
