# Generated by Django 4.2.6 on 2023-10-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0007_alter_compra_subtotal_alter_compra_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport4all.tallaproducto'),
        ),
    ]
