# Generated by Django 4.2.6 on 2023-10-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0008_alter_compraproducto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('en proceso', 'EN PROCESO'), ('entregado', 'ENTREGADO'), ('cancelado', 'CANCELADO'), ('pagado', 'PAGADO')], default='en proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='status',
            field=models.CharField(choices=[('pendiente', 'PENDIENTE'), ('aceptada', 'ACEPTADA'), ('rechazada', 'RECHAZADA'), ('finalizada', 'FINALIZADA')], default='pendiente', max_length=20),
        ),
    ]
