# Generated by Django 4.2.6 on 2023-10-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport4all', '0009_alter_compra_status_alter_devolucion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='status',
            field=models.CharField(choices=[('procesando', 'PROCESANDO'), ('preparando', 'PREPARANDO'), ('en transito', 'EN TRANSITO'), ('entregado', 'ENTREGADO')], default='procesando', max_length=20),
        ),
    ]
